Update static.yml

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -21,22 +21,54 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  # Single deploy job since we're just deploying
-  deploy:
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
+  #CI
+  build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+         if [ -f "${{github.workspace }}/package.json" ]; then
+          echo "::set-output name=manager::npm"
+          echo "::set-output name=command::ci"
+          exit 0
+         else
+          echo "Unable to determine package manager"
+          exit 1
+         fi 
+         
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:          
+          node-version: "16"
+          cache: ${{steps.detect-package-manager.outputs.manager}}
+          
       - name: Setup Pages
+        id: pages
         uses: actions/configure-pages@v2
+        
+      - name: Install dependencies
+        run: ${{steps.detect-package-manager.outputs.manager}} ${{steps.detect-package-manager.outputs.command}}
+        
+      - name: Build
+        run: ${{steps.detect-package-manager.outputs.manager}} run build
+        
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v1
         with:
-          # Upload entire repository
-          path: '.'
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v1
+         path: './public'
+         
+#CD
+  deploy:
+   environment:
+    name: github-pages
+    url: ${{steps.deployment.outputs.page_url}}
+   runs-on: ubuntu-latest
+   needs: build
+   steps:
+    - name: Deploy to Github Pages
+      id: deployment
+      uses: actions/deploy-pages@v1
+         
